version: "3.7"
services: 
  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    build: 
      context: . 
      dockerfile: ./Dockerfile
    environment:

      MSSQL_SA_PASSWORD: "12345__Password!" # LOCAL DEV ONLY!
      ACCEPT_EULA: "Y"

